### ISSUE TITLE
Testaccounts voor Brent en Madjida aanmaken

### ISSUE THREAD

**Issue by MadjidaVIL** [GemeenteUtrecht/bereikbaarheid-backend#32]
Gezien wij beheersrechten hebben kunnen wij niet zaken die opgeleverd zijn testen. Er is een bug bij het weghalen van Tezza documentenbeheer rechten. Graag een testaccount maken.

**Comment by sidneygijzen** [comment]
hallo @MadjidaVIL ,

De bereikbaarheidskaart API doet niets met Tezza documentenbeheer. Ik vermoed dat je vraag hoort in de [zaakafhandelcomponent](https://github.com/GemeenteUtrecht/zaakafhandelcomponent) repository?
